type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  lastLogin: Timestamp
  profilePictureUrl: String
}

type Goal @table {
  user: User!
  name: String!
  startDate: Date!
  createdAt: Timestamp!
  description: String
  targetDate: Date
  isAchieved: Boolean
}

type Habit @table {
  user: User!
  goal: Goal!
  name: String!
  frequency: String!
  createdAt: Timestamp!
  description: String
  isArchived: Boolean
}

type HabitLog @table {
  user: User!
  habit: Habit!
  logDate: Date!
  createdAt: Timestamp!
  notes: String
}

type AIRecommendation @table {
  user: User!
  recommendationText: String!
  createdAt: Timestamp!
  status: String!
  relatedGoalId: UUID
  relatedHabitId: UUID
}